eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost/eureka/
server:
  port: 8890
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: consumer-feign
    api-b:
      path: /api-b/**
      serviceId: consumer-ribbon